### ISSUE TITLE
[iOS + Android] - autoload current location in pick-up field

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#3]
if users want to change it, they can but it would be easier if we autoload their current current location

**Comment by cuong-ubesim** [comment]
Maybe, we should introduce an option in Settings to let rider decide whether he wants to turn this option either on or off. How do you guys think?

**Comment by nguyendtt** [comment]
Lyft has current location auto-populated as the default, however my address shows up slightly off on their app (same neighborhood, wrong address).  I think we should auto-populate the current address by default however shows the address on the field instead of just "Current Location" so user can update if it's not correct @trietphamvm @phuong37

**Comment by phuong37** [comment]
team - i agree with chi trinh that we should auto-load the address and not label it "current location." also, on lyft, you can click on the pin and have it load the address. anh @cuong-ubesim, i think it would be a good feature to auto-load address even if it's not 100% accurate because users are used to seeing that in all of the mapping apps out there - it has become expected now. what do you think?

**Comment by nguyendtt** [comment]
I agree with @phuong37 .  @trietphamvm , can we just update this ticket as an enhancement for both android and iOS? If not, I will create a separate one for iOS. Thanks.

**Comment by trietphamvm** [comment]
please create another ticket for ios, we have difference team for these platforms, please don't forget to have [iOS] - and [Android] - in front of title for easy categorize. Thanks.

**Comment by cuong-ubesim** [comment]
Done.

**Comment by nguyendtt** [comment]
Still not 100% accurate dependding on where I sit in the house but it is close enough. Closing.
